trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Cats Connect'
    contents: |
      **
      !CommentSection/**/*
      !GetComments/**/*
      !.vscode/**/*
      !*.json
      !*.yml
      !*.md
      !.funcignore
      !.gitignore
      !LICENSE
      !.git/**/*
    targetFolder: '/usr/share/caddy2'
    cleanTargetFolder: true
    readyTimeout: '20000'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))