trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Cats Connect'
    contents: 'index.html'
    targetFolder: '/usr/share/caddy2'
    cleanTargetFolder: true
    readyTimeout: '20000'
  
